stack:
  registry:
    name: mdns

  gateway:
    address: :8080 # gateway serve address
    handler: "meta"
    resolver: "stack"
    rpc_path: "/rpc"
    api_path: "/"
    proxy_path: "/{service:[a-zA-Z0-9]+}"
    namespace: "stack.rpc.api"
    header_prefix: "X-Stack-"
    enable_rpc: true
    enable_acme: false
    enable_tls: false
    acme:
      provider: "autocert"
      challenge_provider: "cloudflare"
      ca: "https://acme-v02.api.letsencrypt.org/directory"
      hosts:
        - ""
    # Plugins
    example:
      key: value
